
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="LASER_RADIUS" value="0.038" />
    <xacro:property name="LASER_HEIGHT" value="0.04" />

    <xacro:property name="LASER_JOINT_X" value="${CAR_LENGTH/2-0.055}" />
    <xacro:property name="LASER_JOINT_Y" value="0" />
    <xacro:property name="LASER_JOINT_Z" value="${CAR_HEIGHT/2 + LASER_HEIGHT/4}" />

    <link name="laserbase">
        <visual>
            <geometry>
                <cylinder radius="${LASER_RADIUS}" length="${LASER_HEIGHT/2}"/>
            </geometry>

            <material name="black">
                <color rgba="0.1 0.1 0.1 0.8"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${LASER_RADIUS}" length="${LASER_HEIGHT/2}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix mass="0.3" radius="${LASER_RADIUS}" length="${LASER_HEIGHT/2}" />
    </link>

    <joint name="laserbase2base_link" type="fixed">
        <parent link="base_link"/>
        <child link="laserbase"/>
        <origin xyz="${LASER_JOINT_X} ${LASER_JOINT_Y} ${LASER_JOINT_Z}"/>
    </joint>

    <gazebo reference="laserbase">
        <material>Gazebo/Black</material>
    </gazebo>

    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${LASER_RADIUS}" length="${LASER_HEIGHT/2}"/>
            </geometry>

            <material name="blue">
                <color rgba="0.1 0.8 0.1 0.8"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${LASER_RADIUS}" length="${LASER_HEIGHT/2}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix mass="0.3" radius="${LASER_RADIUS}" length="${LASER_HEIGHT/2}" />
    </link>
    <joint name="laser_joint" type="continuous">
        <parent link="laserbase"/>
        <child link="laser"/>
        <origin xyz="0 0 ${LASER_HEIGHT/2}"/>
        <axis xyz="0 0 1"/>
    </joint>
    <gazebo reference="laser">
        <material>Gazebo/SkyBlue</material>
    </gazebo>
</robot>





