<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="bot">
    <xacro:include filename="inertia.urdf.xacro"/>
    <xacro:include filename="material.urdf.xacro"/>

    <xacro:include filename="bot_wheel.urdf.xacro"/>
    <xacro:include filename="bot_base.urdf.xacro"/>
    <xacro:include filename="bot_lidar.urdf.xacro"/>
    <xacro:include filename="bot_camera.urdf.xacro"/>
    <xacro:include filename="bot_depth.urdf.xacro"/>
    <xacro:sensor_d455 parent="base_link_3" use_nominal_extrinsics="false">
        <origin xyz="${bot_length/2-0.026/2} 0 ${bot_height/2}" rpy="0 0 0"/>
    </xacro:sensor_d455>

    <xacro:include filename="bot_imu.urdf.xacro"/>
    <xacro:imu_n100 parent="base_link_2">
        <origin xyz="0 0 ${bot_height/2}" rpy="0 0 0"/>
    </xacro:imu_n100>

    <xacro:include filename="bot_gazebo.xacro"/>
    <xacro:include filename="bot_gazebo_plugin.xacro"/>

</robot>