<?xml version="1.0"?>
<robot name="imu_n100" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="imu_n100" params="parent *origin">
        <xacro:property name="n100_base_width" value="0.0595"/>
        <xacro:property name="n100_base_height" value="0.005"/>
        <xacro:property name="n100_base_length" value="0.046"/>

        <xacro:property name="n100_width" value="0.04"/>
        <xacro:property name="n100_height" value="0.0067"/>
        <xacro:property name="n100_length" value="${n100_base_length}"/>

        <xacro:property name="n100_mass" value="0.0067"/>
        <link name="n100_base_footprint"/>
        <joint name="n100_base_joint1" type="fixed">
            <xacro:insert_block name="origin" />
            <parent link="${parent}"/>
            <child link="n100_base_footprint"/>
        </joint>



        <link name="n100_base_link">
            <visual>
                <geometry>
                    <box size="${n100_base_length} ${n100_base_width} ${n100_base_height}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${n100_base_length} ${n100_base_width} ${n100_base_height}"/>
                </geometry>
            </collision>
            <xacro:box_inertial_matrix mass="${n100_mass/2}" length="${n100_base_length}" width="${n100_base_width}" height="${n100_base_height}" />
        </link>

        <joint name="n100_base_joint" type="fixed">
            <origin xyz="0.0 0.0 ${n100_base_height/2}"/>
            <xacro:insert_block name="origin" />
            <parent link="n100_base_footprint"/>
            <child link="n100_base_link"/>
        </joint>

        
        <link name="imu_n100">
            <visual>
                <geometry>
                    <box size="${n100_length} ${n100_width} ${n100_height}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${n100_length} ${n100_width} ${n100_height}"/>
                </geometry>
            </collision>
            <xacro:box_inertial_matrix mass="${n100_mass/2}" length="${n100_length}" width="${n100_width}" height="${n100_height}" />
        </link>

        <joint name="n100_joint" type="fixed">
            <origin xyz="0.0 0.0 ${n100_base_height/2+n100_height/2}"/>
            <parent link="n100_base_link"/>
            <child link="imu_n100"/>
        </joint>

    </xacro:macro>
</robot>
