
<robot name="lidar" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_radius" value="0.038" />
    <xacro:property name="lidar_height" value="0.04" />

    <xacro:macro name="lidar_func" params="parent *origin">

        <link name="lidar_base_footprint"/>
        <joint name="lidar_footprint_joint" type="fixed">
            <xacro:insert_block name="origin" />
            <parent link="${parent}"/>
            <child link="lidar_base_footprint"/>
        </joint>

        <link name="lidarbase">
            <visual>
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_height/2}"/>
                </geometry>

                <material name="black">
                    <color rgba="0.1 0.1 0.1 0.8"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_height/2}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertial_matrix mass="0.3" radius="${lidar_radius}" length="${lidar_height/2}" />
        </link>

        <joint name="lidarbase2base_footprint" type="fixed">
            <parent link="lidar_base_footprint"/>
            <child link="lidarbase"/>
            <!-- <origin xyz="${lidar_joint_x} ${lidar_joint_y} ${lidar_joint_z}"/> -->
        </joint>

        <link name="lidar">
            <visual>
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_height/2}"/>
                </geometry>
                <material name="purple"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_height/2}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertial_matrix mass="0.3" radius="${lidar_radius}" length="${lidar_height/2}" />
        </link>
        <joint name="lidar_joint" type="fixed">
            <parent link="lidarbase"/>
            <child link="lidar"/>
            <origin xyz="0 0 ${lidar_height/2}"/>
            <axis xyz="0 0 1"/>
        </joint>

    </xacro:macro>
</robot>




