

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="CAMERA_RADIUS" value="0.07" />
    <xacro:property name="FOOTHOLD_RADIUS" value="0.111" />
    <xacro:property name="FOOTHOLD_HEIGHT" value="0.005" />

    <link name="foothold_base_1">
        <visual>
            <geometry>
                <cylinder radius="${FOOTHOLD_RADIUS}" length="${FOOTHOLD_HEIGHT}"/>
            </geometry>
            <material name="black" />
        </visual>
    </link>

    <joint name="foothold_base1_2_base_link2" type="fixed">
        <parent link="base_link_2"/>
        <child link="foothold_base_1"/>
        <origin xyz="0.0 0.0 0.0"/>
    </joint>


    <link name="foothold_base_2">
        <visual>
            <geometry>
                <box size="${FOOTHOLD_HEIGHT} 0.05 0.23"/>
            </geometry>
            <material name="black" />
        </visual>
    </link>
    <joint name="foothold_base12_joint" type="fixed">
        <parent link="foothold_base_1"/>
        <child link="foothold_base_2"/>
        <origin xyz="${-FOOTHOLD_RADIUS+0.001} 0.0 0.115"/>
    </joint>


    <link name="foothold_base_3">
        <visual>
            <geometry>
                <box size="0.06 0.05 ${FOOTHOLD_HEIGHT}"/>
            </geometry>
            <material name="black" />
        </visual>
    </link>
    <joint name="foothold_base23_joint" type="fixed">
        <parent link="foothold_base_2"/>
        <child link="foothold_base_3"/>
        <origin xyz="0.03 0.0 0.115"/>
    </joint>

    <link name="foothold_base_4">
        <visual>
            <geometry>
                <cylinder radius="0.07" length="${FOOTHOLD_HEIGHT}"/>
            </geometry>
            <material name="black" />
        </visual>
    </link>
    <joint name="foothold_base34_joint" type="fixed">
        <parent link="foothold_base_3"/>
        <child link="foothold_base_4"/>
        <origin xyz="0.1 0.0 0.0"/>
    </joint>

    
    <link name="camera_link">
        <visual>
            <geometry>
                <cylinder radius="0.02" length="0.07"/>
            </geometry>
            <material name="white" />
        </visual>
    </link>
    <joint name="camera_link2foothold4" type="continuous">
        <parent link="foothold_base_4"/>
        <child link="camera_link"/>
        <origin xyz="0.0 0.0 -0.035"/>
        <axis xyz="0.0 0.0 1"/>
    </joint>


    <link name="camera">
        <visual>
            <geometry>
                <sphere radius="${CAMERA_RADIUS}"/>
            </geometry>
            <material name="white"/>
        </visual>
    </link>
    <joint name="camera_link2camera" type="fixed">
        <parent link="camera_link"/>
        <child link="camera"/>
        <origin xyz="0.0 0.0 ${-(CAMERA_RADIUS+0.035)}"/>
    </joint>

</robot>